/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class CHANGE_PASSWORD extends javax.swing.JFrame {
   String type=null;

    /**
     * Creates new form CHANGE_PASSWORD
     */
    public CHANGE_PASSWORD(String usertype) {
        initComponents();
        
        type=usertype;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFUSERNAME = new javax.swing.JTextField();
        CHANGE = new javax.swing.JButton();
        jPF_EXISTING_PASSWORD = new javax.swing.JPasswordField();
        jPF_NEW_PASSWORD = new javax.swing.JPasswordField();
        jPF_CONFIRM_PASSWORD = new javax.swing.JPasswordField();
        BACK = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(385, 360));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USERNAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 40, 70, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EXISTING PASSWORD");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 90, 119, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NEW PASSWORD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 140, 91, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CONFIRM PASSWORD");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 190, 118, 14);
        getContentPane().add(jTFUSERNAME);
        jTFUSERNAME.setBounds(230, 30, 100, 30);

        CHANGE.setText("CHANGE");
        CHANGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHANGEActionPerformed(evt);
            }
        });
        getContentPane().add(CHANGE);
        CHANGE.setBounds(70, 260, 90, 30);
        getContentPane().add(jPF_EXISTING_PASSWORD);
        jPF_EXISTING_PASSWORD.setBounds(230, 80, 100, 30);
        getContentPane().add(jPF_NEW_PASSWORD);
        jPF_NEW_PASSWORD.setBounds(230, 130, 100, 30);
        getContentPane().add(jPF_CONFIRM_PASSWORD);
        jPF_CONFIRM_PASSWORD.setBounds(230, 180, 100, 30);

        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        getContentPane().add(BACK);
        BACK.setBounds(220, 260, 80, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/black_texture_3-wallpaper-1366x768.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 370, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CHANGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHANGEActionPerformed
   
    String uname=jTFUSERNAME.getText();   
    String strpass=jPF_EXISTING_PASSWORD.getText();
    String newpass=jPF_NEW_PASSWORD.getText();
    String conpass=jPF_CONFIRM_PASSWORD.getText();
    
    try
    {   
        Class.forName("java.sql.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","admin");
        Statement st=conn.createStatement();
        ResultSet rs=st.executeQuery("Select username,password from login where username='"+uname+"';");
        if(rs.next())
        {
            String usrname=rs.getString("username");
            String passwd=rs.getString("password");
            

                if(strpass.equals(passwd) && newpass.equals(conpass))
                {
                    Statement st1=conn.createStatement();
                    String sql="UPDATE login SET password='"+newpass+"' where username='"+usrname+"';";
                    st1.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "PASSWORD UPDATE SUCCESSFUL");
                    jTFUSERNAME.setText("");
                    jPF_EXISTING_PASSWORD.setText("");
                    jPF_NEW_PASSWORD.setText("");
                    jPF_CONFIRM_PASSWORD.setText("");
                }
                else if (uname.equals(null) || strpass.equals(null) || newpass.equals(null))
            {
                JOptionPane.showMessageDialog(null, "PLEASE ENTER ALL INFORMATION!!!");
            }
                else
                {
                    JOptionPane.showMessageDialog(null, "PLEASE CONFIRM OLD AND NEW PASSWORD!!!");
                   
                }
                
            }
   
        }

            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
    }//GEN-LAST:event_CHANGEActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
          
        if(type.equals("Admin"))
        {
            new mainpage().setVisible(true);
        }
        else if(type.equals("User"))
        {
            new mainpage1().setVisible(true);
        }
         
        dispose();
    }//GEN-LAST:event_BACKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CHANGE_PASSWORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CHANGE_PASSWORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CHANGE_PASSWORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CHANGE_PASSWORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JButton CHANGE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPF_CONFIRM_PASSWORD;
    private javax.swing.JPasswordField jPF_EXISTING_PASSWORD;
    private javax.swing.JPasswordField jPF_NEW_PASSWORD;
    private javax.swing.JTextField jTFUSERNAME;
    // End of variables declaration//GEN-END:variables
}