/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class NEW_USER extends javax.swing.JFrame {

    /**
     * Creates new form NEW_USER
     */
    public NEW_USER() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTFEpass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jTFNewuser = new javax.swing.JTextField();
        jTFNewpass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTFExisting = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        BACK = new javax.swing.JButton();
        SIGN_UP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);
        jPanel1.add(jTFEpass);
        jTFEpass.setBounds(190, 210, 127, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NEW USERNAME :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 30, 100, 31);

        jTFNewuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNewuserActionPerformed(evt);
            }
        });
        jPanel1.add(jTFNewuser);
        jTFNewuser.setBounds(190, 30, 128, 40);

        jTFNewpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNewpassActionPerformed(evt);
            }
        });
        jPanel1.add(jTFNewpass);
        jTFNewpass.setBounds(190, 90, 128, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NEW PASSWORD :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 100, 100, 21);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EXISTING USER :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 160, 92, 21);
        jPanel1.add(jTFExisting);
        jTFExisting.setBounds(190, 150, 128, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PASSWORD :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 220, 83, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("USER TYPE :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 280, 83, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ADMIN", "EMPLOYEE" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(190, 270, 127, 40);

        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        jPanel1.add(BACK);
        BACK.setBounds(220, 340, 74, 31);

        SIGN_UP.setText("SIGN UP");
        SIGN_UP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIGN_UPActionPerformed(evt);
            }
        });
        jPanel1.add(SIGN_UP);
        SIGN_UP.setBounds(70, 340, 88, 31);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/black_texture_3-wallpaper-1366x768.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 360, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SIGN_UPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIGN_UPActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","admin");
            Statement stmt=conn.createStatement();
            String new_username=jTFNewuser.getText();
            String new_password=jTFNewpass.getText();
            String existing_user=jTFExisting.getText();
            String existing_pass=jTFEpass.getText();
            String user_type=jComboBox2.getSelectedItem().toString();
            String sql="select * from login where username='"+existing_user+"';";
            ResultSet rs=stmt.executeQuery(sql);
            //String password=rs.getString("password");
            if(rs.next())
            {
                String Password=rs.getString("Password");
                if(existing_pass.equals(Password))
                {
                    String sqlinsert="insert into login values('"+new_username+"','"+new_password+"','"+user_type+"');";
                    stmt.executeUpdate(sqlinsert);
                    JOptionPane.showMessageDialog(this,"new user created....!!!");
                    jTFNewuser.setText(null);
                    jTFNewpass.setText(null);
                    jTFExisting.setText(null);
                    jTFEpass.setText(null);
                   
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"check existing username or password");

                }
            }

        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }

    }//GEN-LAST:event_SIGN_UPActionPerformed

    private void jTFNewpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNewpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNewpassActionPerformed

    private void jTFNewuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNewuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNewuserActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
       new login_page().setVisible(true);
       dispose();
    }//GEN-LAST:event_BACKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NEW_USER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NEW_USER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NEW_USER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NEW_USER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NEW_USER().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JButton SIGN_UP;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jTFEpass;
    private javax.swing.JTextField jTFExisting;
    private javax.swing.JPasswordField jTFNewpass;
    private javax.swing.JTextField jTFNewuser;
    // End of variables declaration//GEN-END:variables
}
