/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Student
 */
public class PACKAGE extends javax.swing.JFrame {

    /**
     * Creates new form PACKAGE
     */
    public PACKAGE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BACK = new javax.swing.JButton();
        SAVE = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTFDuration = new javax.swing.JTextField();
        jTFPrice = new javax.swing.JTextField();
        jTFPackage = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD PACKAGE");
        setPreferredSize(new java.awt.Dimension(538, 330));
        getContentPane().setLayout(null);

        BACK.setBackground(new java.awt.Color(0, 0, 0));
        BACK.setForeground(new java.awt.Color(255, 255, 255));
        BACK.setText(" BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        getContentPane().add(BACK);
        BACK.setBounds(190, 240, 80, 30);

        SAVE.setBackground(new java.awt.Color(0, 0, 0));
        SAVE.setForeground(new java.awt.Color(255, 255, 255));
        SAVE.setText(" SAVE");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });
        getContentPane().add(SAVE);
        SAVE.setBounds(40, 240, 76, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DURATION");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 170, 100, 30);
        getContentPane().add(jTFDuration);
        jTFDuration.setBounds(170, 170, 120, 30);
        getContentPane().add(jTFPrice);
        jTFPrice.setBounds(170, 120, 120, 30);
        getContentPane().add(jTFPackage);
        jTFPackage.setBounds(170, 70, 120, 30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PACKAGE NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 70, 130, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PRICE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 120, 100, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/black_texture_3-wallpaper-1366x768.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 630, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        new mainpage().setVisible(true);
          dispose();
    }//GEN-LAST:event_BACKActionPerformed

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        try
        {
            Class.forName("java.sql.Driver");
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","admin");
    
            Statement stmt=conn.createStatement();
    
            String Package_name=jTFPackage.getText();
            int ePrice=Integer.parseInt(jTFPrice.getText());
            String Duration=jTFDuration.getText();
    	
            String sql = "INSERT INTO Package VALUES('"+Package_name+"','"+ePrice+"','"+Duration+"');";
            
            stmt.executeUpdate(sql);
            
    	    JOptionPane.showMessageDialog(this, "Record successfully inserted");
             jTFDuration.setText("");
             jTFPackage.setText("");
             jTFPrice.setText("");
    	
    }
    
catch(Exception a)
    {
        
    JOptionPane.showMessageDialog(this, "Database Connection Error.....!");
    
    }

    
    }//GEN-LAST:event_SAVEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PACKAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PACKAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PACKAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PACKAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PACKAGE().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JButton SAVE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTFDuration;
    private javax.swing.JTextField jTFPackage;
    private javax.swing.JTextField jTFPrice;
    // End of variables declaration//GEN-END:variables
}
